/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PluginPanel.java
 *
 * Created on Nov 10, 2011, 4:59:41 PM
 */

package edu.buffalo.cse.sneps3.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import org.jdesktop.swingx.MultiSplitLayout; 
import org.jdesktop.swingx.JXMultiSplitPane;

/**
 *
 * @author dan
 */
public class PluginPanel extends javax.swing.JPanel {

    RDockComponent semantic;
    SemanticTypesPanel stPanel = new SemanticTypesPanel();

    RDockComponent cf;
    CaseframesPanel cfPanel;

    RDockComponent context;
    ContextsPanel ctPanel;

    JXMultiSplitPane multiSplitPane = new JXMultiSplitPane();
    ArrayList<Component> components = new ArrayList<Component>();

    /** Creates new form PluginPanel */
    public PluginPanel() {
        initComponents();
        this.setLayout(new BorderLayout());
        //this.add(new JLabel("Hi"), BorderLayout.CENTER);
//        String layoutDef =
//    "(COLUMN top bottom)";
//MultiSplitLayout.Node modelRoot = MultiSplitLayout.parseModel(layoutDef);

//MultiSplitPane multiSplitPane = new MultiSplitPane();
//multiSplitPane.getMultiSplitLayout().setModel(modelRoot);
//multiSplitPane.add(new JButton("Left Column"), "top");
//multiSplitPane.add(new JButton("Bottom Row"), "bottom");
//this.add(multiSplitPane, BorderLayout.CENTER);
        addDefaultComponents();
    }



        public void addDefaultComponents(){
                //Semantic Types
        semantic = new RDockComponent();
        //RelationFrame rl = new RelationFrame(null, null, 5, 5, 5, 5);
        semantic.setComponentName("Semantic Types");
        //semantic.setLocation(0, 0);
        semantic.setSize(100, 200);
        semantic.setComponent(stPanel);
        this.addComponent(semantic);
        GUI2.model.registerView(stPanel);


        //Caseframes
        cfPanel = new CaseframesPanel();
        cf = new RDockComponent();
        cf.setComponentName("Caseframes");
        //cf.setLocation(0, semantic.getHeight());
        cf.setSize(100,200);
        cf.setComponent(cfPanel);
        this.addComponent(cf);


        //Contexts
        ctPanel = new ContextsPanel();
        context = new RDockComponent();
        context.setComponentName("Contexts");
        //context.setLocation(0, semantic.getHeight()+cf.getHeight());
        context.setSize(100,200);
        context.setComponent(ctPanel);
        this.addComponent(context);
        GUI2.model.registerView(ctPanel);
    }


    public void addComponent(Component c){
        components.add(c);
        if(components.size() > 1){
            String layoutDef = "(COLUMN ";
            for(int i = 0 ; i < components.size(); i++) layoutDef += "c"+i+" ";
            layoutDef += ")";
            MultiSplitLayout.Node modelRoot = MultiSplitLayout.parseModel(layoutDef);
            multiSplitPane = new JXMultiSplitPane();
            multiSplitPane.getMultiSplitLayout().setModel(modelRoot);
            for(int i = 0 ; i < components.size(); i++){
                multiSplitPane.add(components.get(i), "c"+i);
            }
            this.removeAll();
            this.add(multiSplitPane, BorderLayout.CENTER);
        }
    }





    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
